### ISSUE TITLE
Lab 4, Exercise 1

### ISSUE THREAD

**Issue by kiminoa** [ericmj/workshop#7]
Forgive the pedantry; hope this'll be useful for future n00bs.

1. "Create a process that just prints the first message it receives with IO.write(:stderr, message)" - I misunderstood this to mean we had to set up receive to look specifically on :stderr channel (instead of intention: any message, and report _that_ to :stderr channel.)
2. "then dies, it should return the pid of the new process." Does solution.ex actually do this part?

**Comment by kiminoa** [comment]
Answer to question 2 - Yes. spawn itself returns pid.

**Comment by ericmj** [comment]
Thanks for the feedback @kiminoa, I updated the exercise text regarding `IO.write/2`.
